language: ruby
rvm:
  - 1.9.3
  - ruby-head
  - rbx-19mode

bundler_args: "--without development production assets"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "cp config/environments/environment.sample.yml config/environments/test.yml"
script:
  - "bundle exec rake ci:tests"
