development: &defaults
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

production:
  <<: *defaults
  database: db/production.sqlite3
